### ISSUE TITLE
Make fails on Tag v1.1?

### ISSUE THREAD

**Issue by ReStone** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#12] opened 2016-09-19 12:37 UTC
I've been not able to build tag v1.1. Make failed with several errors:

[cmake_and_make_outputs.txt](https://github.com/ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter/files/479945/c_and_make.txt)

**Comment by killenb** [comment] 2016-09-20 14:15
I cannot reproduce this isse. tag v1.1 as well as the trunk are compiling fine for me, incl. all dependencies on Ubuntu 16. Which host system are you using? Did you use a fresh checkout?

**Comment by ichrispa** [comment] 2016-09-20 16:00
Someone on the open62541 had introduced an error that caused the namespace compiler to fail. They where quite right about their bugfix, so it took some time to adapt both open62541 and the namespace compiler to allow building of namespaces again.

I fixed it just a couple of hours ago, it should all work again.

**Comment by killenb** [comment] 2016-09-20 17:05
Aren't we using a tag? Tags should never change. Or are we using a release candidate branch?

**Comment by ichrispa** [comment] 2016-09-20 17:25
open62541 is closely infront of a release, so 0.2 is currently considered rc2. It should be released within the month, which means we will have a stable line for our production rc.

**Comment by ReStone** [comment] 2016-09-20 19:29
Thanks for the fix. Build is working fine again - like it did last weekend :).
But the built application quits with a segmentation error - what it not did last weekend :(.
![segfault](https://cloud.githubusercontent.com/assets/19655759/18685639/3e70564c-7f79-11e6-9d61-88284311a37f.PNG)

For reference I captured the whole installation process:
[installlog.txt](https://github.com/ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter/files/483451/installlog.txt)

**Comment by jmrahm** [comment] 2016-09-21 06:32
From now on, it should work fine. The segmentation error was also reasoned by open62541.

**Comment by ReStone** [comment] 2016-09-21 12:17
Yes, everything is working now. Thank you!

**Closed** 2016-09-22 11:02 UTC
