### ISSUE TITLE
double nodes in UaExpert

### ISSUE THREAD

**Issue by ReStone** [ChimeraTK/ControlSystemAdapter-OPC-UA-Adapter#10] opened 2016-08-25 14:48 UTC
UaExpert sees all Root/Objects/Server - nodes twice in the DemoServer (Tag v1.0) adress space:
![double nodes](https://cloud.githubusercontent.com/assets/19655759/17973625/79b5c12e-6ae3-11e6-80eb-45b05cc7b9e9.PNG)

Is that wanted behaviour?

**Comment by jmrahm** [comment] 2016-09-09 14:28
Issue #3 from report.
Working in progress ;-)

**Comment by ichrispa** [comment] 2016-09-20 16:01
The cause was found and fixed in open62541. The duplicated should be gone now.

**Comment by ichrispa** [comment] 2016-09-22 11:10
Still occuring in subdirectories (Telco), reopened.

**Comment by zenker** [comment] 2023-02-17 13:13
Fixed long time ago.

**Closed by zenker** 2023-02-17 13:13 UTC
